/**
 * Editorial topic roadmap. This is planning data, not a queue of articles to generate.
 * One row can cover several keyword variants that share the same intent.
 */
export const TOPIC_ROADMAP = [
  {
    id: "picture-to-pdf-iphone",
    title: "How to Convert a Picture to PDF on iPhone",
    primaryKeyword: "convert picture to PDF on iPhone",
    supportingKeywords: ["photo to PDF iPhone", "image to PDF iPhone", "pic to PDF iPhone", "heic to PDF iPhone"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "image-to-pdf",
    priority: "P1",
    relatedSearches: ["save photo as PDF iPhone", "print to PDF iPhone Photos"],
    relatedTools: ["image-to-pdf", "heic-to-jpg", "merge-pdf"],
  },
  {
    id: "pdf-to-word-iphone",
    title: "How to Convert PDF to Word on iPhone",
    primaryKeyword: "convert PDF to Word on iPhone",
    supportingKeywords: ["PDF to Word iPhone", "PDF to docx iPhone Safari"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "pdf-to-word",
    priority: "P1",
    relatedSearches: ["edit PDF as Word on iPhone", "PDF to Pages iPhone"],
    relatedTools: ["pdf-to-word", "word-to-pdf", "unlock-pdf"],
  },
  {
    id: "word-to-pdf-iphone",
    title: "How to Convert Word to PDF on iPhone",
    primaryKeyword: "convert Word to PDF on iPhone",
    supportingKeywords: ["docx to PDF iPhone", "Word document to PDF Safari"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "word-to-pdf",
    priority: "P1",
    relatedSearches: ["Pages export PDF iPhone", "save Word as PDF iPhone"],
    relatedTools: ["word-to-pdf", "pdf-to-word", "compress-pdf"],
  },
  {
    id: "pdf-to-jpg-iphone",
    title: "How to Convert PDF to JPG on iPhone",
    primaryKeyword: "convert PDF to JPG on iPhone",
    supportingKeywords: ["PDF to image iPhone", "PDF page to photo iPhone"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "pdf-to-jpg",
    priority: "P1",
    relatedSearches: ["save PDF page to Photos", "PDF screenshot iPhone"],
    relatedTools: ["pdf-to-jpg", "pdf-to-png", "image-to-pdf"],
  },
  {
    id: "heic-to-jpg-iphone",
    title: "How to Convert HEIC to JPG on iPhone",
    primaryKeyword: "convert HEIC to JPG on iPhone",
    supportingKeywords: ["HEIC to JPEG iPhone", "iPhone photo to JPG"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "heic-to-jpg",
    priority: "P1",
    relatedSearches: ["Windows cannot open HEIC", "change iPhone camera to JPEG"],
    relatedTools: ["heic-to-jpg", "image-to-jpg", "image-to-pdf"],
  },
  {
    id: "merge-pdf-iphone",
    title: "How to Merge PDF Files on iPhone",
    primaryKeyword: "merge PDF on iPhone",
    supportingKeywords: ["combine PDFs iPhone", "join PDF files Safari"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "merge-pdf",
    priority: "P1",
    relatedSearches: ["put two PDFs together iPhone", "combine Files PDFs"],
    relatedTools: ["merge-pdf", "split-pdf", "compress-pdf"],
  },
  {
    id: "split-pdf-iphone",
    title: "How to Split a PDF on iPhone",
    primaryKeyword: "split PDF on iPhone",
    supportingKeywords: ["extract PDF pages iPhone", "separate PDF pages Safari"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "split-pdf",
    priority: "P1",
    relatedSearches: ["delete PDF pages iPhone", "save one page from PDF"],
    relatedTools: ["split-pdf", "merge-pdf", "compress-pdf"],
  },
  {
    id: "compress-pdf-iphone",
    title: "How to Compress a PDF on iPhone",
    primaryKeyword: "compress PDF on iPhone",
    supportingKeywords: ["reduce PDF size iPhone", "make PDF smaller Safari"],
    searchIntent: "how-to",
    deviceIntent: "iphone",
    toolDependency: "compress-pdf",
    priority: "P1",
    relatedSearches: ["PDF too large for email iPhone", "compress PDF without uploading"],
    relatedTools: ["compress-pdf", "split-pdf", "pdf-to-jpg"],
  },
  { id: "pdf-to-png-iphone", title: "PDF to PNG on iPhone", primaryKeyword: "PDF to PNG iPhone", supportingKeywords: ["lossless PDF image iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-png", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-png", "pdf-to-jpg"] },
  { id: "extract-images-iphone", title: "Extract images from a PDF on iPhone", primaryKeyword: "extract images from PDF iPhone", supportingKeywords: ["pull photos out of PDF"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "extract-images", priority: "P2", relatedSearches: [], relatedTools: ["extract-images", "pdf-to-jpg"] },
  { id: "pdf-to-excel-iphone", title: "PDF to Excel on iPhone", primaryKeyword: "convert PDF to Excel on iPhone", supportingKeywords: ["PDF table to spreadsheet iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-excel", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-excel"] },
  { id: "pdf-to-ppt-iphone", title: "PDF to PowerPoint on iPhone", primaryKeyword: "PDF to PowerPoint iPhone", supportingKeywords: ["PDF to PPT iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-ppt", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-ppt"] },
  { id: "pdf-to-epub-iphone", title: "PDF to EPUB on iPhone", primaryKeyword: "PDF to EPUB iPhone", supportingKeywords: ["PDF to ebook iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-ebook", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-ebook"] },
  { id: "rotate-pdf-iphone", title: "Rotate a PDF on iPhone", primaryKeyword: "rotate PDF iPhone", supportingKeywords: ["fix sideways PDF iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "rotate-pdf", priority: "P2", relatedSearches: [], relatedTools: ["rotate-pdf"] },
  { id: "sign-pdf-iphone", title: "Sign a PDF on iPhone", primaryKeyword: "sign PDF on iPhone", supportingKeywords: ["add signature to PDF Safari"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "sign-pdf", priority: "P2", relatedSearches: [], relatedTools: ["sign-pdf"] },
  { id: "protect-pdf-iphone", title: "Password-protect a PDF on iPhone", primaryKeyword: "password protect PDF iPhone", supportingKeywords: ["lock PDF iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "protect-pdf", priority: "P2", relatedSearches: [], relatedTools: ["protect-pdf", "unlock-pdf"] },
  { id: "unlock-pdf-iphone", title: "Unlock a PDF on iPhone", primaryKeyword: "unlock PDF iPhone", supportingKeywords: ["remove PDF password iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "unlock-pdf", priority: "P2", relatedSearches: [], relatedTools: ["unlock-pdf", "protect-pdf"] },
  { id: "image-to-jpg-iphone", title: "Convert an image to JPG on iPhone", primaryKeyword: "convert image to JPG iPhone", supportingKeywords: ["PNG to JPG iPhone"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "image-to-jpg", priority: "P2", relatedSearches: [], relatedTools: ["image-to-jpg", "heic-to-jpg"] },
  { id: "scan-document-iphone", title: "Scan a document to PDF on iPhone", primaryKeyword: "scan document to PDF iPhone", supportingKeywords: ["Notes scan PDF", "Files scan document"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "none", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf", "compress-pdf"] },
  { id: "print-to-pdf-iphone", title: "Print to PDF on iPhone", primaryKeyword: "print to PDF iPhone", supportingKeywords: ["Save as PDF Share sheet"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "none", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "pdf-to-word-android", title: "Convert PDF to Word on Android", primaryKeyword: "convert PDF to Word on Android", supportingKeywords: ["PDF to Word Chrome Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "picture-to-pdf-android", title: "Convert a picture to PDF on Android", primaryKeyword: "photo to PDF Android", supportingKeywords: ["image to PDF Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "image-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "merge-pdf-android", title: "Merge PDFs on Android", primaryKeyword: "merge PDF Android", supportingKeywords: ["combine PDF Chrome"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "merge-pdf", priority: "P2", relatedSearches: [], relatedTools: ["merge-pdf"] },
  { id: "split-pdf-android", title: "Split a PDF on Android", primaryKeyword: "split PDF Android", supportingKeywords: ["extract PDF pages Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "split-pdf", priority: "P2", relatedSearches: [], relatedTools: ["split-pdf"] },
  { id: "compress-pdf-android", title: "Compress a PDF on Android", primaryKeyword: "compress PDF Android", supportingKeywords: ["reduce PDF size Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "compress-pdf", priority: "P2", relatedSearches: [], relatedTools: ["compress-pdf"] },
  { id: "word-to-pdf-android", title: "Word to PDF on Android", primaryKeyword: "Word to PDF Android", supportingKeywords: ["docx to PDF Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "word-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["word-to-pdf"] },
  { id: "pdf-to-jpg-android", title: "PDF to JPG on Android", primaryKeyword: "PDF to JPG Android", supportingKeywords: ["PDF to image Android"], searchIntent: "how-to", deviceIntent: "android", toolDependency: "pdf-to-jpg", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-jpg"] },
  { id: "pdf-to-word-windows", title: "Convert PDF to Word on Windows", primaryKeyword: "convert PDF to Word Windows", supportingKeywords: ["PDF to Word browser"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "picture-to-pdf-windows", title: "Convert a picture to PDF on Windows", primaryKeyword: "image to PDF Windows", supportingKeywords: ["JPG to PDF browser"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "image-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "merge-pdf-windows", title: "Merge PDFs on Windows", primaryKeyword: "merge PDF Windows", supportingKeywords: ["combine PDFs browser"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "merge-pdf", priority: "P2", relatedSearches: [], relatedTools: ["merge-pdf"] },
  { id: "heic-to-jpg-windows", title: "Open iPhone HEIC photos on Windows", primaryKeyword: "convert HEIC to JPG Windows", supportingKeywords: ["HEIC Windows cannot open"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "heic-to-jpg", priority: "P2", relatedSearches: [], relatedTools: ["heic-to-jpg"] },
  { id: "pdf-to-word-mac", title: "Convert PDF to Word on Mac", primaryKeyword: "convert PDF to Word Mac", supportingKeywords: ["PDF to Word Safari Mac"], searchIntent: "how-to", deviceIntent: "mac", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "picture-to-pdf-mac", title: "Convert a picture to PDF on Mac", primaryKeyword: "image to PDF Mac", supportingKeywords: ["Preview vs browser PDF"], searchIntent: "how-to", deviceIntent: "mac", toolDependency: "image-to-pdf", priority: "P3", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "merge-pdf-mac", title: "Merge PDFs on Mac", primaryKeyword: "merge PDF Mac", supportingKeywords: ["combine PDFs Preview"], searchIntent: "compare", deviceIntent: "mac", toolDependency: "merge-pdf", priority: "P3", relatedSearches: [], relatedTools: ["merge-pdf"] },
  { id: "empty-word-from-pdf", title: "The Word file from a PDF is empty", primaryKeyword: "PDF to Word empty file", supportingKeywords: ["OCR scanned PDF failed"], searchIntent: "troubleshoot", deviceIntent: "any", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word", "pdf-to-jpg"] },
  { id: "safari-download-missing", title: "The converted file did not download in Safari", primaryKeyword: "Safari PDF download missing", supportingKeywords: ["in-app browser download blocked"], searchIntent: "troubleshoot", deviceIntent: "iphone", toolDependency: "none", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "password-pdf-convert", title: "Convert a password-protected PDF", primaryKeyword: "convert password protected PDF", supportingKeywords: ["unlock PDF then convert"], searchIntent: "how-to", deviceIntent: "any", toolDependency: "unlock-pdf", priority: "P2", relatedSearches: [], relatedTools: ["unlock-pdf", "pdf-to-word"] },
  { id: "pdf-too-large-email", title: "PDF too large to email from iPhone", primaryKeyword: "PDF too large for email iPhone", supportingKeywords: ["Mail attachment limit PDF"], searchIntent: "troubleshoot", deviceIntent: "iphone", toolDependency: "compress-pdf", priority: "P2", relatedSearches: [], relatedTools: ["compress-pdf", "split-pdf"] },
  { id: "heic-wont-open", title: "Someone cannot open an iPhone photo", primaryKeyword: "HEIC will not open", supportingKeywords: ["send iPhone photo as JPG"], searchIntent: "troubleshoot", deviceIntent: "iphone", toolDependency: "heic-to-jpg", priority: "P2", relatedSearches: [], relatedTools: ["heic-to-jpg"] },
  { id: "what-is-heic", title: "What HEIC is, in practice", primaryKeyword: "what is HEIC", supportingKeywords: ["HEIC vs JPG iPhone"], searchIntent: "explain", deviceIntent: "iphone", toolDependency: "heic-to-jpg", priority: "P3", relatedSearches: [], relatedTools: ["heic-to-jpg"] },
  { id: "browser-vs-app", title: "Browser PDF tools vs App Store converters", primaryKeyword: "PDF converter without app iPhone", supportingKeywords: ["Safari PDF tools"], searchIntent: "compare", deviceIntent: "iphone", toolDependency: "none", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "files-stay-on-device", title: "Where the file is processed", primaryKeyword: "PDF converter that does not upload", supportingKeywords: ["browser PDF privacy"], searchIntent: "explain", deviceIntent: "any", toolDependency: "none", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "ocr-on-iphone", title: "Scanned PDFs and OCR on iPhone", primaryKeyword: "OCR PDF on iPhone", supportingKeywords: ["scanned PDF to Word iPhone"], searchIntent: "explain", deviceIntent: "iphone", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "pdf-to-excel-tables", title: "When PDF to Excel finds no table", primaryKeyword: "PDF to Excel no table found", supportingKeywords: ["extract table from PDF"], searchIntent: "troubleshoot", deviceIntent: "any", toolDependency: "pdf-to-excel", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-excel"] },
  { id: "compress-did-not-shrink", title: "Compress PDF made the file larger", primaryKeyword: "compress PDF larger file", supportingKeywords: ["PDF already compressed"], searchIntent: "troubleshoot", deviceIntent: "any", toolDependency: "compress-pdf", priority: "P2", relatedSearches: [], relatedTools: ["compress-pdf", "split-pdf"] },
  { id: "merge-order", title: "Control the order when merging PDFs", primaryKeyword: "merge PDF page order", supportingKeywords: ["rearrange PDFs before merge"], searchIntent: "how-to", deviceIntent: "any", toolDependency: "merge-pdf", priority: "P3", relatedSearches: [], relatedTools: ["merge-pdf"] },
  { id: "iphone-files-picker", title: "Safari cannot see the PDF", primaryKeyword: "Safari cannot find PDF in Files", supportingKeywords: ["Save to Files from Mail"], searchIntent: "troubleshoot", deviceIntent: "iphone", toolDependency: "none", priority: "P1", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "jpg-vs-png-from-pdf", title: "PDF to JPG vs PDF to PNG", primaryKeyword: "PDF to JPG vs PNG", supportingKeywords: ["which image format from PDF"], searchIntent: "compare", deviceIntent: "any", toolDependency: "pdf-to-jpg", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-jpg", "pdf-to-png"] },
  { id: "image-pdf-vs-print", title: "Photos Print to PDF vs Image to PDF", primaryKeyword: "print photo to PDF vs converter", supportingKeywords: ["multiple photos one PDF"], searchIntent: "compare", deviceIntent: "iphone", toolDependency: "image-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "word-doc-vs-docx", title: "Old .doc files will not convert", primaryKeyword: "doc to PDF iPhone", supportingKeywords: ["save as docx first"], searchIntent: "troubleshoot", deviceIntent: "any", toolDependency: "word-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["word-to-pdf"] },
  { id: "sign-vs-markup", title: "Markup signature vs embedded PDF signature", primaryKeyword: "sign PDF Markup vs converter", supportingKeywords: ["iPhone Markup PDF signature"], searchIntent: "compare", deviceIntent: "iphone", toolDependency: "sign-pdf", priority: "P3", relatedSearches: [], relatedTools: ["sign-pdf"] },
  { id: "protect-vs-unlock", title: "Lock and unlock a PDF you own", primaryKeyword: "password PDF iPhone", supportingKeywords: ["remember PDF password"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "protect-pdf", priority: "P3", relatedSearches: [], relatedTools: ["protect-pdf", "unlock-pdf"] },
  { id: "pdf-to-word-windows-desktop", title: "PDF to Word in Edge or Chrome", primaryKeyword: "PDF to Word in browser", supportingKeywords: ["no install PDF to Word"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "pdf-to-word", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "compress-windows", title: "Compress a PDF on Windows", primaryKeyword: "compress PDF Windows browser", supportingKeywords: ["reduce PDF size Chrome"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "compress-pdf", priority: "P3", relatedSearches: [], relatedTools: ["compress-pdf"] },
  { id: "split-windows", title: "Split a PDF on Windows", primaryKeyword: "split PDF Windows", supportingKeywords: ["extract pages PDF browser"], searchIntent: "how-to", deviceIntent: "windows", toolDependency: "split-pdf", priority: "P3", relatedSearches: [], relatedTools: ["split-pdf"] },
  { id: "android-files-picker", title: "Chrome on Android cannot see the PDF", primaryKeyword: "Android Chrome PDF picker empty", supportingKeywords: ["Downloads vs Files Android"], searchIntent: "troubleshoot", deviceIntent: "android", toolDependency: "none", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "mac-preview-vs-browser", title: "When Preview is enough on Mac", primaryKeyword: "Preview vs online PDF tools Mac", supportingKeywords: ["merge PDF Preview"], searchIntent: "compare", deviceIntent: "mac", toolDependency: "none", priority: "P3", relatedSearches: [], relatedTools: ["merge-pdf", "pdf-to-jpg"] },
  { id: "rotate-scanned-pages", title: "Fix sideways scanned pages before converting", primaryKeyword: "rotate scanned PDF then convert", supportingKeywords: ["OCR sideways page"], searchIntent: "how-to", deviceIntent: "any", toolDependency: "rotate-pdf", priority: "P3", relatedSearches: [], relatedTools: ["rotate-pdf", "pdf-to-word"] },
  { id: "multi-page-jpg-zip", title: "PDF to JPG downloads a ZIP", primaryKeyword: "PDF to JPG ZIP download", supportingKeywords: ["multiple PDF pages images"], searchIntent: "explain", deviceIntent: "any", toolDependency: "pdf-to-jpg", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-jpg"] },
  { id: "icloud-drive-pdf", title: "Use a PDF stored in iCloud Drive", primaryKeyword: "convert iCloud Drive PDF iPhone", supportingKeywords: ["Files iCloud PDF Safari"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "none", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "whatsapp-pdf", title: "Convert a PDF received in WhatsApp", primaryKeyword: "WhatsApp PDF to Word iPhone", supportingKeywords: ["Save to Files WhatsApp PDF"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "mail-pdf", title: "Convert a PDF from Mail on iPhone", primaryKeyword: "Mail PDF to Word iPhone", supportingKeywords: ["email attachment PDF convert"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "photos-to-one-pdf", title: "Several iPhone photos in one PDF", primaryKeyword: "multiple photos to one PDF iPhone", supportingKeywords: ["receipt photos PDF"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "image-to-pdf", priority: "P1", relatedSearches: [], relatedTools: ["image-to-pdf", "compress-pdf"] },
  { id: "form-only-accepts-pdf", title: "A form only accepts PDF, you have photos", primaryKeyword: "upload photos as PDF", supportingKeywords: ["application form photo PDF"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "image-to-pdf", priority: "P2", relatedSearches: [], relatedTools: ["image-to-pdf"] },
  { id: "cv-pdf-to-word", title: "Turn a CV PDF into a Word file", primaryKeyword: "CV PDF to Word iPhone", supportingKeywords: ["resume PDF editable"], searchIntent: "how-to", deviceIntent: "iphone", toolDependency: "pdf-to-word", priority: "P2", relatedSearches: [], relatedTools: ["pdf-to-word"] },
  { id: "excel-from-statement", title: "Get a table out of a bank-style PDF", primaryKeyword: "PDF statement to Excel", supportingKeywords: ["when tables are not real tables"], searchIntent: "how-to", deviceIntent: "any", toolDependency: "pdf-to-excel", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-excel"] },
  { id: "pptx-from-slides", title: "PDF slides into PowerPoint", primaryKeyword: "PDF slides to PowerPoint", supportingKeywords: ["each page becomes a slide image"], searchIntent: "explain", deviceIntent: "any", toolDependency: "pdf-to-ppt", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-ppt"] },
  { id: "epub-limitations", title: "What PDF to EPUB actually keeps", primaryKeyword: "PDF to EPUB limitations", supportingKeywords: ["reflow PDF ebook"], searchIntent: "explain", deviceIntent: "any", toolDependency: "pdf-to-ebook", priority: "P3", relatedSearches: [], relatedTools: ["pdf-to-ebook"] },
  { id: "unlock-not-crack", title: "Unlock only works with the password you know", primaryKeyword: "remove PDF password you know", supportingKeywords: ["cannot bypass PDF encryption"], searchIntent: "explain", deviceIntent: "any", toolDependency: "unlock-pdf", priority: "P2", relatedSearches: [], relatedTools: ["unlock-pdf"] },
  { id: "file-size-limits", title: "File size and page limits in the tools", primaryKeyword: "PDF converter file size limit", supportingKeywords: ["25 MB PDF iPhone"], searchIntent: "explain", deviceIntent: "any", toolDependency: "none", priority: "P2", relatedSearches: [], relatedTools: ["compress-pdf", "split-pdf"] },
  { id: "related-convert-cluster", title: "Pick the right conversion for a photo, Word file, or PDF", primaryKeyword: "which PDF converter do I need", supportingKeywords: ["image PDF Word JPG"], searchIntent: "compare", deviceIntent: "any", toolDependency: "none", priority: "P3", relatedSearches: [], relatedTools: ["image-to-pdf", "word-to-pdf", "pdf-to-word", "pdf-to-jpg"] },
];

export function getTopic(id) {
  return TOPIC_ROADMAP.find((item) => item.id === id) || null;
}

export const FIRST_EIGHT_TOPIC_IDS = [
  "picture-to-pdf-iphone",
  "pdf-to-word-iphone",
  "word-to-pdf-iphone",
  "pdf-to-jpg-iphone",
  "heic-to-jpg-iphone",
  "merge-pdf-iphone",
  "split-pdf-iphone",
  "compress-pdf-iphone",
];
